#!/bin/bash

if [ $1 = "inc" ]; then
  $(brightnessctl s 10%+);
else
  $(brightnessctl s 10%-);
fi

brightness=$(brightnessctl g);
max=$(brightnessctl m);
cur=$(($brightness*100/$max));

notify-send "Brightness" -i xfpm-brightness-lcd -t 100 -h int:value:$cur