#!/bin/bash

touch private/index;

for f in $(find private/ -type f ! -name '*.enc' ! -name 'index'); do
  fullsum=$(echo $f | sha256sum);
  location=${f/private\//""};
  hash=$(echo $fullsum | cut -f1 -d " ");

  echo ${fullsum/-/$location} >> private/index;
  keybase pgp encrypt -i $f -o vault/$hash.enc;
done

keybase pgp encrypt -i private/index -o vault/index.enc;
rm private/index;
